### ISSUE TITLE
Update to newest or newest-ish (stable) versions

### ISSUE THREAD

**Issue by kvirani** [lighthouse-labs/node-skeleton#4]
Many of the dependencies, including node itself, should be updated

Extensive testing should be done WITHIN the student vagrant machine to make sure this works (end-to-end; make no assumptions)

Remember to update the README.md as well, and maybe improve the dependency list in the process.

**Comment by jholman** [comment]
As a side note, it'd be really nice if we could update the node-sass dependency (indirect dependency via node-sass-middleware) to v5.x, but we cannot, because it's not out yet.  But it'd be nice if we could, because via some long dependency chain, it includes hoek 2.x.x, which triggers angry messages from `npm audit`, and thus from github.  So if that releases, let's be sure to do something about that.
